version: '3.9'

services:
  datebase:
    image: postgres:17
    container_name: datebase
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: asX77hiv-14
      POSTGRES_DB: medical
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: backend
    
    environment:
      DATABASE_URL: postgres+asyncpg://postgres:asX77hiv-14@datebase:5432/medical
      DB_HOST: datebase
      DB_USER: postgres
      DB_PASS: asX77hiv-14
      DB_NAME: medical
      DB_PORT: 5432
      SECRET_KEY_TOKEN: 09d25e094faaasdkdjvncjkxloieif213jhg7099f6f0f4caa6cf63b88e8d3e7
      ALGORITHM: HS256
    depends_on:
      datebase:
        condition: service_healthy
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - frontend
      - backend

volumes:
  db_data:
