networks:
  dev:

services:
  nginx:
    image: nginx:slim
    ports:
      - "8080:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - '/etc/letsencrypt:/etc/letsencrypt'
    depends_on:
      - backend
      - frontend
    networks:
      - dev

  backend:
    container_name: backend
    build:
      context: ./python_files
    networks:
      - dev
    environment:
      DATABASE_URL: postgres://postgres:asX77hiv-14@host.docker.internal:5432/stud

  frontend:
    build:
      context: ./frontend
    networks:
      - dev

  db:
    image: postgres:latest
    networks:
      - dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: asX77hiv-14
      POSTGRES_DB: stud
