"""change rols

Revision ID: 7faad7dc1946
Revises: a9247ed50d1a
Create Date: 2024-12-18 03:22:39.515359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from config import medic, dispatcher

# revision identifiers, used by Alembic.
revision: str = '7faad7dc1946'
down_revision: Union[str, None] = 'a9247ed50d1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()

    # Удаление привилегий для dispatcher
    conn.execute(sa.text("REVOKE CONNECT ON DATABASE medical FROM dispatcher;"))
    conn.execute(sa.text("REVOKE USAGE ON SCHEMA public FROM dispatcher;"))
    conn.execute(sa.text("REVOKE SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public FROM dispatcher;"))
    conn.execute(sa.text("DROP ROLE dispatcher;"))

    # Удаление привилегий для medic
    conn.execute(sa.text("REVOKE CONNECT ON DATABASE medical FROM medic;"))
    conn.execute(sa.text("REVOKE USAGE ON SCHEMA public FROM medic;"))
    conn.execute(sa.text("REVOKE SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public FROM medic;"))
    conn.execute(sa.text("DROP ROLE medic;"))

    # Удаление ролей
    conn.execute(sa.text(f"DROP ROLE IF EXISTS {medic};"))
    conn.execute(sa.text(f"DROP ROLE IF EXISTS {dispatcher};"))

    # Создание ролей с входом и паролем
    conn.execute(sa.text(f"CREATE ROLE {medic} WITH LOGIN PASSWORD 'medic_password';"))
    conn.execute(sa.text(f"CREATE ROLE {dispatcher} WITH LOGIN PASSWORD 'dispatcher_password';"))

    # Разрешение подключения к базе данных
    conn.execute(sa.text(f"GRANT CONNECT ON DATABASE medical TO {medic};"))
    conn.execute(sa.text(f"GRANT CONNECT ON DATABASE medical TO {dispatcher};"))

    # Разрешение использования схемы public
    conn.execute(sa.text(f"GRANT USAGE ON SCHEMA public TO {medic};"))
    conn.execute(sa.text(f"GRANT USAGE ON SCHEMA public TO {dispatcher};"))

    # Предоставление привилегий для medic
    conn.execute(sa.text(f"GRANT SELECT ON report TO {medic};"))
    conn.execute(sa.text(f"GRANT SELECT ON call TO {medic};"))
    conn.execute(sa.text(f"GRANT SELECT ON statuscall TO {medic};"))
    conn.execute(sa.text(f"GRANT SELECT, INSERT ON users TO {medic};"))
    conn.execute(sa.text(f"REVOKE ALL ON brigades FROM {medic};"))
    conn.execute(sa.text(f"REVOKE ALL ON cars FROM {medic};"))
    conn.execute(sa.text(f"REVOKE ALL ON compositionsbrigades FROM {medic};"))

    # Предоставление привилегий для dispatcher
    conn.execute(sa.text(f"GRANT SELECT, INSERT, UPDATE ON brigades TO {dispatcher};"))
    conn.execute(sa.text(f"GRANT SELECT, INSERT, UPDATE ON cars TO {dispatcher};"))
    conn.execute(sa.text(f"GRANT SELECT, INSERT ON users TO {dispatcher};"))
    conn.execute(sa.text(f"GRANT SELECT, INSERT ON compositionsbrigades TO {dispatcher};"))
    conn.execute(sa.text(f"REVOKE ALL ON report FROM {dispatcher};"))
    conn.execute(sa.text(f"REVOKE ALL ON call FROM {dispatcher};"))
    conn.execute(sa.text(f"REVOKE ALL ON statuscall FROM {dispatcher};"))

    # Запрет доступа к secret_data
    conn.execute(sa.text(f"REVOKE ALL ON secret_data FROM {medic};"))
    conn.execute(sa.text(f"REVOKE ALL ON secret_data FROM {dispatcher};"))

    # Привилегии на будущие таблицы
    conn.execute(sa.text(f"ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE ON TABLES TO {medic};"))
    conn.execute(
        sa.text(f"ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE ON TABLES TO {dispatcher};"))
    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()

    # Удаление привилегий для dispatcher
    conn.execute(sa.text("REVOKE CONNECT ON DATABASE medical FROM dispatcher;"))
    conn.execute(sa.text("REVOKE USAGE ON SCHEMA public FROM dispatcher;"))
    conn.execute(sa.text("REVOKE SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public FROM dispatcher;"))
    conn.execute(sa.text("DROP ROLE dispatcher;"))

    # Удаление привилегий для medic
    conn.execute(sa.text("REVOKE CONNECT ON DATABASE medical FROM medic;"))
    conn.execute(sa.text("REVOKE USAGE ON SCHEMA public FROM medic;"))
    conn.execute(sa.text("REVOKE SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public FROM medic;"))
    conn.execute(sa.text("DROP ROLE medic;"))
    # ### end Alembic commands ###
