"""initial migration

Revision ID: c7f3927fca74
Revises: 
Create Date: 2024-12-17 21:34:44.566818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7f3927fca74'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('main_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('operation_type', sa.String(), nullable=False),
    sa.Column('operation_date', sa.String(), nullable=False),
    sa.Column('user_operator', sa.String(), nullable=False),
    sa.Column('changed_data', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('time_reaction', sa.String(), nullable=False),
    sa.Column('workload', sa.Enum('low', 'med', 'high', name='workload'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('secret_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('statuscall',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('dispatcher', 'medic', 'admin', name='role'), nullable=False),
    sa.Column('qualification', sa.Enum('first', 'med', 'primary', name='qualification'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compositionsbrigades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('driver', sa.Integer(), nullable=False),
    sa.Column('paramedic', sa.Integer(), nullable=False),
    sa.Column('nurse', sa.Integer(), nullable=False),
    sa.Column('orderly', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['driver'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['nurse'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['orderly'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paramedic'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brigades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('composition_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['composition_id'], ['compositionsbrigades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('call',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('time_call', sa.DateTime(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('dispatcher_id', sa.Integer(), nullable=False),
    sa.Column('brigade_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['brigade_id'], ['brigades.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dispatcher_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['status_id'], ['statuscall.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cars',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Enum('free', 'repair', 'busy', name='statuscar'), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('brigade_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['brigade_id'], ['brigades.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cars')
    op.drop_table('call')
    op.drop_table('brigades')
    op.drop_table('compositionsbrigades')
    op.drop_table('users')
    op.drop_table('statuscall')
    op.drop_table('secret_data')
    op.drop_table('report')
    op.drop_table('main_log')
    # ### end Alembic commands ###
